version: '3.8'

services:
  telegram-bot:
    image: python:3.9-slim
    container_name: simple-telebot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python app.py"
